name: lab-without-installer
on:
  workflow_dispatch:
    inputs:
      RUNNER:
        description: 'Runner Name'
        required: true
        default: 'u08'
      INFRAPARAMFILE:
        description: 'infraparamfile'
        required: false
        default: paramfiles/lab.yml
      EXTRAPARAMS:
        description: 'Extra params'
        default: ''
      PARAMFILE:
        description: 'paramfile'
        required: false
        default: paramfiles/lab_without_installer.yml
      PULLSECRET:
        description: 'pullsecret'
        required: false
        default: /root/openshift_pull.json
      VERSION:
        description: 'version'
        required: false
        default: stable
      TAG:
        description: 'tag'
        required: false
        default: "4.11"

env:
 HOME: /root
 PYTHONUNBUFFERED: true
 CLIENT: ${{github.event.inputs.CLIENT}}
 PLAN: lab
 INFRAPARAMFILE: ${{github.event.inputs.INFRAPARAMFILE}}
 PARAMFILE: ${{github.event.inputs.PARAMFILE}}
 EXTRAPARAMS: ${{github.event.inputs.EXTRAPARAMS}}
 PULLSECRET: ${{github.event.inputs.PULLSECRET}}
 VERSION: ${{github.event.inputs.VERSION}}
 TAG: ${{github.event.inputs.TAG}}

jobs:
    requirements:
      runs-on: ${{github.event.inputs.RUNNER}}
      steps:
       - uses: actions/checkout@v2
       - run: git pull origin ${GITHUB_REF##*/}
       - name: Install kcli
         run: |
           curl https://raw.githubusercontent.com/karmab/kcli/master/install.sh | bash
           # kcli create pool -p /var/lib/libvirt/images default
           # sudo setfacl -m u:$(id -un):rwx /var/lib/libvirt/images

    deploy-infra-plan:
      needs: requirements
      runs-on: ${{github.event.inputs.RUNNER}}
      steps:
       - name: Deploy infra
         run: kcli create plan --force -f kcli_plan_infra.yml --paramfile $INFRAPARAMFILE $PLAN

    install-redfish:
      needs: deploy-infra-plan
      runs-on: ${{github.event.inputs.RUNNER}}
      steps:
       - name: Render sushy
         run: kcli render -f helpers/sushy.conf --paramfile $INFRAPARAMFILE > /etc/sushy.conf
       - name: Install redfish
         run: |
           pip3 install sushy-tools
           cp -f helpers/sushy.service /usr/lib/systemd/system
           ### temp hack ###
           sed -i 's@8000@80@' /etc/sushy.conf
           systemctl restart sushy
           #################
           # systemctl enable --now sushy

    render-redfish-in-parameter-file:
      needs: install-redfish
      runs-on: ${{github.event.inputs.RUNNER}}
      steps:
       - name: Render redfish in parameter file
         run: kcli render -f virtual_platform_hosts.yml --paramfile $INFRAPARAMFILE --paramfile $PARAMFILE >> $PARAMFILE

    deploy-cluster:
      needs: render-redfish-in-parameter-file
      runs-on: ${{github.event.inputs.RUNNER}}
      steps:
       - name: Deploy cluster
         run: |
           ### temp hack ###
           sed -i 's@:8000@:80@' $PARAMFILE
           #################
           kcli --debug create cluster openshift --paramfile $PARAMFILE -P pull_secret="$PULLSECRET" $PLAN-cluster $EXTRAPARAMS --force
