name: lab-ipv6
on:
  workflow_dispatch:
    inputs:
      RUNNER:
        description: 'Runner Name'
        required: true
        default: 'libvirt'
      CLIENT:
        description: 'Client name'
        required: true
        default: 'local'
      INPUTFILE:
        description: 'Input file'
        required: true
        default: kcli_plan.yml
      PARAMFILE:
        description: 'paramfile'
        required: false
        default: paramfiles/lab_ipv6.yml
      EXTRAPARAMS:
        description: 'Extra params'
        default: ''
      PULL_SECRET:
        description: 'pull_secret'
        required: false
        default: /root/openshift_pull.json
      LAUNCH_STEPS:
        description: 'launch_steps'
        required: false
        default: True
      DEPLOY_HUB:
        description: 'deploy_hub'
        required: false
        default: True
      VERSION:
        description: 'version'
        required: false
        default: stable
      TAG:
        description: 'tag'
        required: false
        default: "4.16"

env:
 HOME: /root
 PYTHONUNBUFFERED: true
 CLIENT: ${{github.event.inputs.CLIENT}}
 PLAN: lab
 INPUTFILE: ${{github.event.inputs.INPUTFILE}}
 PARAMFILE: ${{github.event.inputs.PARAMFILE}}
 EXTRAPARAMS: ${{github.event.inputs.EXTRAPARAMS}}
 PULL_SECRET: ${{github.event.inputs.PULL_SECRET}}
 LAUNCH_STEPS: ${{github.event.inputs.LAUNCH_STEPS}}
 DEPLOY_HUB: ${{github.event.inputs.DEPLOY_HUB}}
 VERSION: ${{github.event.inputs.VERSION}}
 TAG: ${{github.event.inputs.TAG}}

jobs:
    requirements:
      runs-on: ${{github.event.inputs.RUNNER}}

      steps:
       - uses: actions/checkout@v3
       - run: git pull origin ${GITHUB_REF##*/}
       - name: Install kcli
         run: |
           curl https://raw.githubusercontent.com/karmab/kcli/master/install.sh | bash
           # kcli create pool -p /var/lib/libvirt/images default
           # sudo setfacl -m u:$(id -un):rwx /var/lib/libvirt/images

    deploy-plan:
      needs: requirements
      runs-on: ${{github.event.inputs.RUNNER}}
      steps:
       - name: Deploy kcli plan
         run: kcli -C $CLIENT create plan --force -f $INPUTFILE --paramfile $PARAMFILE -P pull_secret=$PULL_SECRET -P launch_steps=$LAUNCH_STEPS -P deploy_hub=$DEPLOY_HUB -P version=$VERSION -P tag=$TAG $EXTRAPARAMS $PLAN
