name: lab-ipv6-ztp-nightly
on:
  schedule:
    - cron: '15 1 * * *'

env:
 HOME: /root
 PYTHONUNBUFFERED: true
 PLAN: lab
 INPUTFILE: plans/kcli_plan_ztp.yml
 PARAMFILE: paramfiles/lab_ipv6_ztp.yml
 PULLSECRET: /root/openshift_pull.json

jobs:
    requirements:
      runs-on: libvirt
      steps:
       - uses: actions/checkout@v2
       - run: git pull origin ${GITHUB_REF##*/}
       - name: Install kcli
         run: |
           curl https://raw.githubusercontent.com/karmab/kcli/master/install.sh | bash
           # kcli create pool -p /var/lib/libvirt/images default
           # sudo setfacl -m u:$(id -un):rwx /var/lib/libvirt/images

    deploy-plan:
      needs: requirements
      runs-on: libvirt
      steps:
        - name: Deploy kcli plan
          run: |
            # temp 4.11 ipv6 hack
            mv manifests/99-ipv6.yaml.sample manifests/99-ipv6.yaml
            kcli create plan --force -f $INPUTFILE --paramfile $PARAMFILE -P pullsecret=$PULLSECRET $PLAN
